project:
  type: website
  output-dir: docs

website:
  title: "Assignment 3_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - proof_of_life.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



